### ISSUE TITLE
Single Location Image Optimization

### ISSUE THREAD

**Issue by scottsousa** [WheatonCollege/map#13]
Looks like [srcset](http://caniuse.com/#feat=srcse) isn't supported across all browsers. We likely can't reiliably use the HTML5 spec for image optimization on different viewport sizes

Resource: http://www.html5rocks.com/en/tutorials/responsive/picture-element/

Tagging @gopperman

**Comment by gopperman** [comment]
We can use it with a fallback, though.

**Comment by scottsousa** [comment]
@gopperman I'm going to implement http://scottjehl.github.io/picturefill/ as the polyfill

**Comment by gopperman** [comment]
Looks good, thanks.

**Comment by scottsousa** [comment]
See https://github.com/WheatonCollege/map/commit/3fa6bb7426fbd8bd34aa7be764cf428df963287a

**Comment by scottsousa** [comment]
Lazy loading and responsive image sizes were implemented in https://github.com/WheatonCollege/map/commit/3fa6bb7426fbd8bd34aa7be764cf428df963287a
