### ISSUE TITLE
"View Larger" button/image caption display

### ISSUE THREAD

**Issue by scottsousa** [WheatonCollege/map#14]
When an image has a caption associated with it, the UI for the "View Larger" button/caption can overflow the container element on some displays. We can adjust the font size and/or the container margin/padding accordingly to fix this.

See attached image:
![image](https://cloud.githubusercontent.com/assets/5098743/8187302/31220a9e-141d-11e5-9292-39ccd78948b9.png)

---

@gopperman I'm thinking the image meta content should always appear vertically centered within the image container. What are your thoughts?

Here are a couple of mock-ups:

![image](https://cloud.githubusercontent.com/assets/5098743/8187606/ac2249c4-141e-11e5-8705-d8d381fee1ef.png)
![image](https://cloud.githubusercontent.com/assets/5098743/8187530/38d0b3ca-141e-11e5-9667-beec2cee4130.png)

**Comment by gopperman** [comment]
We want the caption to be at-most one sentence. I'd rather limit the number of characters in the custom field. It's really intended to just be a short title of what you're looking at.

**Comment by scottsousa** [comment]
The character limit should be around 40 characters or so for best results.

**Comment by scottsousa** [comment]
This issue has been addressed in https://github.com/WheatonCollege/map/commit/6c0765f75541336eff5bb33b26c2e5e716ea4447
