### ISSUE TITLE
Building List / Filtering

### ISSUE THREAD

**Issue by gopperman** [WheatonCollege/map#18]

**Comment by scottsousa** [comment]
A majority of this tech was implemented in:

* https://github.com/WheatonCollege/map/commit/6c0765f75541336eff5bb33b26c2e5e716ea4447
* https://github.com/WheatonCollege/map/commit/e8ac49a0b29df2b7ef1abbc8dabb097902418187
* https://github.com/WheatonCollege/map/commit/f35ca6fef472df44870a2c19b8a977f306c0dd8f

We're just waiting on confirmation from Suzanne on the mobile viewport design to finish.

**Comment by scottsousa** [comment]
@gopperman I'm not sure if we have any feedback or not for this yet. Any updates?

**Comment by gopperman** [comment]
I have a short QA list from Suz that I'll be working on. I think this can be closed, there's an issue open and assigned to me.
