### ISSUE TITLE
Building Pins and Hover State

### ISSUE THREAD

**Issue by gopperman** [WheatonCollege/map#22]
Implement these features on the main map page...Depends on #5

**Comment by sdsweb** [comment]
Are we building the coordinate system or are you Greg? Still not clear to me.

**Comment by gopperman** [comment]
We can go over it on next week's call, but right now you guys are putting
the coordinates into the CMS, correct?

**Comment by sdsweb** [comment]
Yup. Okay, we'll discuss more next week.

**Comment by gopperman** [comment]
Sounds good. When you get a chance, update the ticket with times that work
for you, if you haven't already.

**Comment by gopperman** [comment]
You know, I think it makes sense to swap a couple of these tasks. We'll catch up on the call.
