### ISSUE TITLE
Test iOS Safari (iPhone)

### ISSUE THREAD

**Issue by gopperman** [WheatonCollege/map#29]

**Comment by scottsousa** [comment]
Single location page footer is "stuck" to bottom of window when scrolling.

**Comment by gopperman** [comment]
Is this in the lightbox? If so, the lightbox just needs a higher z-index.

**Comment by scottsousa** [comment]
@gopperman This actually is occurring on all devices that we've tested on so it's not specific to iPhone. At first, I thought it was only happening on the iPhone. Do you want me to create a separate issue for general QA items?

Here's a screenshot on desktop:

![image](https://cloud.githubusercontent.com/assets/5098743/8483081/09ea55c0-20bc-11e5-9812-aace2aade741.png)

**Comment by gopperman** [comment]
Yeah, you can create a seperate issue for QA items. This one is pretty
simple, location pages shouldn't get the header and footer since they'll be
pulled in via lightbox.
