### ISSUE TITLE
Populate staging with stubs locations for each building

### ISSUE THREAD

**Issue by gopperman** [WheatonCollege/map#3]

**Comment by gopperman** [comment]
Depends on #2

**Comment by scottsousa** [comment]
@gopperman This task is being handled by the Communications department, correct?

**Comment by gopperman** [comment]
Yes

**Comment by scottsousa** [comment]
@gopperman Thanks for the clarification. I will leave this issue open until all of the locations have been finalized.

**Comment by gopperman** [comment]
Chris just let me know that the locations are all in, with at least some placeholder info. Many buildings have actual content.
