### ISSUE TITLE
Lazy load gallery images on building detail page

### ISSUE THREAD

**Issue by gopperman** [WheatonCollege/map#4]

**Comment by scottsousa** [comment]
Potential candidate for lazy loading images: [This plugin](https://wordpress.org/plugins/rocket-lazy-load/) is made from the guys who make the WP Rocket caching plugin.

**Comment by gopperman** [comment]
When possible we're going to prefer to include javascript-based plugins
directly, rather than through Wordpress. This keeps everything in our nice,
jslinted pipeline.

**Comment by scottsousa** [comment]
I've implemented [lazysizes](https://github.com/aFarkas/lazysizes) for lazy loading images based on its support for `<picture>` elements.

**Comment by scottsousa** [comment]
See https://github.com/WheatonCollege/map/commit/3fa6bb7426fbd8bd34aa7be764cf428df963287a

**Comment by scottsousa** [comment]
Lazy loading via the lazysizes.js library was implemented in https://github.com/WheatonCollege/map/commit/3fa6bb7426fbd8bd34aa7be764cf428df963287a
