### ISSUE TITLE
Quicklook lightbox links now require a double click to open lightbox

### ISSUE THREAD

**Issue by scottsousa** [WheatonCollege/map#40]
This occurred after: https://github.com/WheatonCollege/map/commit/e93d659cb35b120a98bbd8ad1f0d092a29564330.

I believe this is the culprit:
https://github.com/WheatonCollege/map/blob/e93d659cb35b120a98bbd8ad1f0d092a29564330/web/app/themes/map/assets/js/_main.js#L59-L66

**Comment by gopperman** [comment]
ok, not fixed in firefox
